import { PERMISSIONS } from '@/contexts/AuthContext';

export const COMPONENT_PERMISSIONS = {
  // Dashboard Components - using employee view as default dashboard permission
  Dashboard: PERMISSIONS.EMPLOYEE_VIEW,
  
  // Employee Management Components
  EmployeeList: PERMISSIONS.EMPLOYEE_VIEW,
  EmployeeDetails: PERMISSIONS.EMPLOYEE_VIEW,
  EmployeeForm: PERMISSIONS.EMPLOYEE_CREATE,
  DepartmentList: PERMISSIONS.DEPARTMENT_VIEW,
  DepartmentForm: PERMISSIONS.DEPARTMENT_CREATE,
  AttendanceList: PERMISSIONS.ATTENDENCE_VIEW,
  AttendanceForm: PERMISSIONS.ATTENDENCE_CREATE,
  PerformanceList: PERMISSIONS.PERFORMANCE_VIEW,
  PerformanceForm: PERMISSIONS.PERFORMANCE_CREATE,
  LeaveList: PERMISSIONS.LEAVE_VIEW,
  LeaveForm: PERMISSIONS.LEAVE_CREATE,
  
  // Hiring Components
  JobList: PERMISSIONS.JOB_VIEW,
  JobForm: PERMISSIONS.JOB_CREATE,
  CandidateList: PERMISSIONS.CANDIDATE_VIEW,
  CandidateForm: PERMISSIONS.CANDIDATE_CREATE,
  InterviewList: PERMISSIONS.INTERVIEW_VIEW,
  InterviewForm: PERMISSIONS.INTERVIEW_CREATE,
  OnboardingList: PERMISSIONS.ONBOARDING_VIEW,
  OnboardingForm: PERMISSIONS.ONBOARDING_CREATE,
  
  // Settings Components
  CompanyProfile: PERMISSIONS.COMPANYPROFILE_VIEW,
  CompanyProfileForm: PERMISSIONS.COMPANYPROFILE_EDIT,
  RolesPermissions: PERMISSIONS.ROLESPERMISIONS_VIEW,
  SystemSettings: PERMISSIONS.SYSTEMSETTINGS_VIEW,
  SystemSettingsForm: PERMISSIONS.SYSTEMSETTINGS_EDIT,
} as const; 