import { PERMISSIONS } from '@/contexts/AuthContext';

export const COMPONENT_PERMISSIONS = {
  // Dashboard Components
  Dashboard: PERMISSIONS.VIEW_DASHBOARD,
  
  // Employee Management Components
  EmployeeList: PERMISSIONS.VIEW_EMPLOYEES,
  EmployeeDetails: PERMISSIONS.VIEW_EMPLOYEE_DETAILS,
  EmployeeForm: PERMISSIONS.MANAGE_EMPLOYEES,
  DepartmentList: PERMISSIONS.VIEW_DEPARTMENTS,
  DepartmentForm: PERMISSIONS.MANAGE_DEPARTMENTS,
  AttendanceList: PERMISSIONS.VIEW_ATTENDANCE,
  AttendanceForm: PERMISSIONS.MANAGE_ATTENDANCE,
  PerformanceList: PERMISSIONS.VIEW_PERFORMANCE,
  PerformanceForm: PERMISSIONS.MANAGE_PERFORMANCE,
  LeaveList: PERMISSIONS.VIEW_LEAVE,
  LeaveForm: PERMISSIONS.MANAGE_LEAVE,
  
  // Hiring Components
  JobList: PERMISSIONS.VIEW_JOBS,
  JobForm: PERMISSIONS.MANAGE_JOBS,
  CandidateList: PERMISSIONS.VIEW_CANDIDATES,
  CandidateForm: PERMISSIONS.MANAGE_CANDIDATES,
  InterviewList: PERMISSIONS.VIEW_INTERVIEWS,
  InterviewForm: PERMISSIONS.MANAGE_INTERVIEWS,
  OnboardingList: PERMISSIONS.VIEW_ONBOARDING,
  OnboardingForm: PERMISSIONS.MANAGE_ONBOARDING,
  
  // Project Components
  ProjectList: PERMISSIONS.VIEW_PROJECTS,
  ProjectForm: PERMISSIONS.MANAGE_PROJECTS,
  TaskList: PERMISSIONS.VIEW_TASKS,
  TaskForm: PERMISSIONS.MANAGE_TASKS,
  SprintList: PERMISSIONS.VIEW_SPRINT_DETAILS,
  SprintForm: PERMISSIONS.EDIT_SPRINT_DETAILS,
  Timeline: PERMISSIONS.VIEW_TIMELINE,
  ResourceList: PERMISSIONS.VIEW_RESOURCES,
  ResourceForm: PERMISSIONS.ALLOCATE_RESOURCES,
  DeliverableList: PERMISSIONS.VIEW_DELIVERABLES,
  DeliverableForm: PERMISSIONS.MANAGE_DELIVERABLES,
  
  // Sales Components
  ClientList: PERMISSIONS.VIEW_CLIENTS,
  ClientForm: PERMISSIONS.MANAGE_CLIENTS,
  ProposalList: PERMISSIONS.VIEW_PROPOSALS,
  ProposalForm: PERMISSIONS.MANAGE_PROPOSALS,
  ContractList: PERMISSIONS.VIEW_CONTRACTS,
  ContractForm: PERMISSIONS.MANAGE_CONTRACTS,
  RevenueList: PERMISSIONS.VIEW_REVENUE_DETAILS,
  RevenueForm: PERMISSIONS.MANAGE_REVENUE,
  
  // Asset Components
  AssetList: PERMISSIONS.VIEW_ASSETS,
  AssetForm: PERMISSIONS.MANAGE_ASSETS,
  LicenseList: PERMISSIONS.VIEW_LICENSES,
  LicenseForm: PERMISSIONS.MANAGE_LICENSES,
  MaintenanceList: PERMISSIONS.VIEW_MAINTENANCE,
  MaintenanceForm: PERMISSIONS.MANAGE_MAINTENANCE,
  
  // Finance Components
  InvoiceList: PERMISSIONS.VIEW_INVOICES,
  InvoiceForm: PERMISSIONS.MANAGE_INVOICES,
  ExpenseList: PERMISSIONS.VIEW_EXPENSES,
  ExpenseForm: PERMISSIONS.MANAGE_EXPENSES,
  PayrollList: PERMISSIONS.VIEW_PAYROLL,
  PayrollForm: PERMISSIONS.MANAGE_PAYROLL,
  ReportList: PERMISSIONS.VIEW_REPORTS,
  ReportForm: PERMISSIONS.MANAGE_REPORTS,
  
  // Settings Components
  CompanyProfile: PERMISSIONS.VIEW_COMPANY_PROFILE,
  CompanyProfileForm: PERMISSIONS.EDIT_COMPANY_PROFILE,
  RolesPermissions: PERMISSIONS.MANAGE_ROLES,
  SystemSettings: PERMISSIONS.VIEW_SYSTEM_SETTINGS,
  SystemSettingsForm: PERMISSIONS.EDIT_SYSTEM_SETTINGS,
} as const; 